project:
  name: "AI Advent With Love"

features:
  thread_history: true

ui:
  name: "AI Advent With Love"
  description: "Ваш интеллектуальный ассистент"
  default_collapse_content: true
  hide_cot: false
  theme:
    light:
      primary: "#5c6bc0"
    dark:
      primary: "#7986cb"
